name: Update README cards

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0" # run every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=AltCover
          path: profile/pin-AltCover.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card 2
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=Gendarme
          path: profile/pin-Gendarme.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card 3
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=altcode.dixon
          path: profile/pin-altcode.dixon.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card 4
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=altcode.test
          path: profile/pin-altcode.test.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card 5
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=altcode.fake
          path: profile/pin-altcode.fake.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push